### ISSUE TITLE
Wordpress on Linux : Docker defaut settings 

### ISSUE THREAD

**Issue by cedrox** [Azure-App-Service/apps#39]
Hello, 
I want to use deflate / gzip apache feature but when I create a default wordpress on linux, my docker is appsvc/apps:apache-php-mysql-0.2. If I understand well I need to use at least appsvc/apps:apache-php-mysql-0.3 to get this feature [https://github.com/Azure-App-Service/apps/blob/master/apache-php-mysql/0.4/httpd.conf]. When I try to update this setting directly into the container parameter, I have a 503 "service unvalaible". 
Moreover, I cannot get access to 2017_11_17_************_docker.log (event when I stop the web app service)
What do I need to do to update my docker container ?

**Comment by grayniall** [comment]
Same here - any news?

**Comment by cedrox** [comment]
Hello, 
Error in my docker.log is :
2017-11-24 09:53:51.596 INFO  - Issuing docker pull: imagename =appsvc/apps:apache-php-mysql-0.4
2017-11-24 09:53:52.506 INFO  - Issuing docker pull: imagename =appsvc/apps:apache-php-mysql-0.4
2017-11-24 09:53:53.400 INFO  - Issuing docker pull appsvc/apps:apache-php-mysql-0.4
2017-11-24 09:53:54.548 ERROR - docker pull returned STDERR>> Error response from daemon: manifest for appsvc/apps:apache-php-mysql-0.4 not found

**Comment by cedrox** [comment]
Look like there is no image for this version available here : 
https://hub.docker.com/r/appsvc/apps/tags/

Can you confirm ?

**Comment by cedrox** [comment]
Hello, 
I manage to build the version 0.4 on a linux docker. I then push it to azure registry and try to consume it from my web app via docker Container setup but it don't work. Docker log :
ERROR - Container SiteName_0 for site SiteName has exited, failing site start
No more info...
When I try to run it locally on Docker for Windows, It doen't work neither...
Is this version work for you ? Have you got any procedure to get this done ?

**Comment by grayniall** [comment]
I managed to get it to work

https://hub.docker.com/r/grayniall/apps/tags/

**Comment by cedrox** [comment]
Building the 0.4 version on you personnal docker hub or to registry is the proper solution right now :) 
More over, you have to don't forget to delete setting WEBSITE_ENABLE_APP_SERVICE_STORAGE = “false” if you activate it. That disabled mounting to storage. You delete this setting from Application settings. Application works after the change.
